mkdir -p ../data/metat/mp_4
mkdir -p ../data/metat/mp_1
mkdir -p ../data/metat/mp_3
mkdir -p ../data/metat/mp_5
mkdir -p ../data/metat/mp_2
mkdir -p ../data/metat/jupiter_mini_borg_1
mkdir -p ../data/metat/jupiter_mini_borg_2
mkdir -p ../data/metat/jupiter_mini_borg_3
mkdir -p ../data/metat/jupiter_mini_borg_4
mkdir -p ../data/metat/jupiter_mini_borg_6
mkdir -p ../data/metat/jupiter_mini_borg_7
mkdir -p ../data/metat/jupiter_mini_borg_8
mkdir -p ../data/metat/jupiter_mini_borg_9
mkdir -p ../data/metat/saturn_mini_borg_1
mkdir -p ../data/metat/saturn_mini_borg_2
mkdir -p ../data/metat/saturn_mini_borg_3
mkdir -p ../data/metat/saturn_mini_borg_4
mkdir -p ../data/metat/unclassified_mini_borg
mkdir -p ../data/metat/unclassified_borg
mkdir -p ../data/metat/amethyst_borg
mkdir -p ../data/metat/oxblood_borg
mkdir -p ../data/metat/pink_borg
mkdir -p ../data/metat/purple_borg
mkdir -p ../data/metat/rose_borg
mkdir -p ../data/metat/vermilion_borg
mkdir -p ../data/metat/mercury_mini_borg
mkdir -p ../data/metat/saturn_mini_borg_like
mkdir -p ../data/metat/ruby_borg_related
mkdir -p ../data/metat/black_borg
mkdir -p ../data/metat/linear_ece_19kb
