featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/ck_bottom_2025_metat_read_counts ~/data/metat/mp_4/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/ck_middle_2025_metat_read_counts ~/data/metat/mp_4/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/ck_top_2025_metat_read_counts ~/data/metat/mp_4/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_top_2025_metat_read_counts ~/data/metat/mp_4/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_bottom_2025_metat_read_counts ~/data/metat/mp_4/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_middle_2025_metat_read_counts ~/data/metat/mp_4/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/ck_bottom_2024_metat_read_counts ~/data/metat/mp_4/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_top_2024_metat_read_counts ~/data/metat/mp_4/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_bottom_2024_metat_read_counts ~/data/metat/mp_4/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_4.gff -s 2 -o ~/data/metat/mp_4/n_middle_2024_metat_read_counts ~/data/metat/mp_4/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/ck_bottom_2025_metat_read_counts ~/data/metat/mp_1/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/ck_middle_2025_metat_read_counts ~/data/metat/mp_1/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/ck_top_2025_metat_read_counts ~/data/metat/mp_1/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_top_2025_metat_read_counts ~/data/metat/mp_1/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_bottom_2025_metat_read_counts ~/data/metat/mp_1/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_middle_2025_metat_read_counts ~/data/metat/mp_1/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/ck_bottom_2024_metat_read_counts ~/data/metat/mp_1/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_top_2024_metat_read_counts ~/data/metat/mp_1/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_bottom_2024_metat_read_counts ~/data/metat/mp_1/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_1.gff -s 2 -o ~/data/metat/mp_1/n_middle_2024_metat_read_counts ~/data/metat/mp_1/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/ck_bottom_2025_metat_read_counts ~/data/metat/mp_3/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/ck_middle_2025_metat_read_counts ~/data/metat/mp_3/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/ck_top_2025_metat_read_counts ~/data/metat/mp_3/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_top_2025_metat_read_counts ~/data/metat/mp_3/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_bottom_2025_metat_read_counts ~/data/metat/mp_3/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_middle_2025_metat_read_counts ~/data/metat/mp_3/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/ck_bottom_2024_metat_read_counts ~/data/metat/mp_3/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_top_2024_metat_read_counts ~/data/metat/mp_3/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_bottom_2024_metat_read_counts ~/data/metat/mp_3/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_3.gff -s 2 -o ~/data/metat/mp_3/n_middle_2024_metat_read_counts ~/data/metat/mp_3/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/ck_bottom_2025_metat_read_counts ~/data/metat/mp_5/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/ck_middle_2025_metat_read_counts ~/data/metat/mp_5/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/ck_top_2025_metat_read_counts ~/data/metat/mp_5/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_top_2025_metat_read_counts ~/data/metat/mp_5/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_bottom_2025_metat_read_counts ~/data/metat/mp_5/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_middle_2025_metat_read_counts ~/data/metat/mp_5/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/ck_bottom_2024_metat_read_counts ~/data/metat/mp_5/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_top_2024_metat_read_counts ~/data/metat/mp_5/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_bottom_2024_metat_read_counts ~/data/metat/mp_5/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_5.gff -s 2 -o ~/data/metat/mp_5/n_middle_2024_metat_read_counts ~/data/metat/mp_5/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/ck_bottom_2025_metat_read_counts ~/data/metat/mp_2/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/ck_middle_2025_metat_read_counts ~/data/metat/mp_2/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/ck_top_2025_metat_read_counts ~/data/metat/mp_2/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_top_2025_metat_read_counts ~/data/metat/mp_2/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_bottom_2025_metat_read_counts ~/data/metat/mp_2/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_middle_2025_metat_read_counts ~/data/metat/mp_2/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/ck_bottom_2024_metat_read_counts ~/data/metat/mp_2/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_top_2024_metat_read_counts ~/data/metat/mp_2/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_bottom_2024_metat_read_counts ~/data/metat/mp_2/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp_2.gff -s 2 -o ~/data/metat/mp_2/n_middle_2024_metat_read_counts ~/data/metat/mp_2/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_1/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_1.gff -s 2 -o ~/data/metat/jupiter_mini_borg_1/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_1/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_2/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_2.gff -s 2 -o ~/data/metat/jupiter_mini_borg_2/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_2/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_3/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_3.gff -s 2 -o ~/data/metat/jupiter_mini_borg_3/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_3/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_4/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_4.gff -s 2 -o ~/data/metat/jupiter_mini_borg_4/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_4/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_6/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_6.gff -s 2 -o ~/data/metat/jupiter_mini_borg_6/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_6/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_7/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_7.gff -s 2 -o ~/data/metat/jupiter_mini_borg_7/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_7/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_8/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_8.gff -s 2 -o ~/data/metat/jupiter_mini_borg_8/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_8/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/ck_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/ck_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/ck_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_top_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_bottom_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_middle_2025_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/ck_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_9/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_top_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_bottom_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/jupiter_mini_borg_9.gff -s 2 -o ~/data/metat/jupiter_mini_borg_9/n_middle_2024_metat_read_counts ~/data/metat/jupiter_mini_borg_9/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/ck_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/ck_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/ck_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/ck_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_1/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_top_2024_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_1.gff -s 2 -o ~/data/metat/saturn_mini_borg_1/n_middle_2024_metat_read_counts ~/data/metat/saturn_mini_borg_1/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/ck_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/ck_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/ck_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/ck_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_2/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_top_2024_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_2.gff -s 2 -o ~/data/metat/saturn_mini_borg_2/n_middle_2024_metat_read_counts ~/data/metat/saturn_mini_borg_2/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/ck_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/ck_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/ck_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/ck_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_3/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_top_2024_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_3.gff -s 2 -o ~/data/metat/saturn_mini_borg_3/n_middle_2024_metat_read_counts ~/data/metat/saturn_mini_borg_3/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/ck_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/ck_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/ck_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/ck_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_4/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_top_2024_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_4.gff -s 2 -o ~/data/metat/saturn_mini_borg_4/n_middle_2024_metat_read_counts ~/data/metat/saturn_mini_borg_4/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/ck_bottom_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/ck_middle_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/ck_top_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_top_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_bottom_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_middle_2025_metat_read_counts ~/data/metat/unclassified_mini_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/ck_bottom_2024_metat_read_counts ~/data/metat/unclassified_mini_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_top_2024_metat_read_counts ~/data/metat/unclassified_mini_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_bottom_2024_metat_read_counts ~/data/metat/unclassified_mini_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_mini_borg.gff -s 2 -o ~/data/metat/unclassified_mini_borg/n_middle_2024_metat_read_counts ~/data/metat/unclassified_mini_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/ck_bottom_2025_metat_read_counts ~/data/metat/unclassified_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/ck_middle_2025_metat_read_counts ~/data/metat/unclassified_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/ck_top_2025_metat_read_counts ~/data/metat/unclassified_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_top_2025_metat_read_counts ~/data/metat/unclassified_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_bottom_2025_metat_read_counts ~/data/metat/unclassified_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_middle_2025_metat_read_counts ~/data/metat/unclassified_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/ck_bottom_2024_metat_read_counts ~/data/metat/unclassified_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_top_2024_metat_read_counts ~/data/metat/unclassified_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_bottom_2024_metat_read_counts ~/data/metat/unclassified_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/unclassified_borg.gff -s 2 -o ~/data/metat/unclassified_borg/n_middle_2024_metat_read_counts ~/data/metat/unclassified_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/ck_bottom_2025_metat_read_counts ~/data/metat/amethyst_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/ck_middle_2025_metat_read_counts ~/data/metat/amethyst_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/ck_top_2025_metat_read_counts ~/data/metat/amethyst_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_top_2025_metat_read_counts ~/data/metat/amethyst_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_bottom_2025_metat_read_counts ~/data/metat/amethyst_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_middle_2025_metat_read_counts ~/data/metat/amethyst_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/ck_bottom_2024_metat_read_counts ~/data/metat/amethyst_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_top_2024_metat_read_counts ~/data/metat/amethyst_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_bottom_2024_metat_read_counts ~/data/metat/amethyst_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/amethyst_borg.gff -s 2 -o ~/data/metat/amethyst_borg/n_middle_2024_metat_read_counts ~/data/metat/amethyst_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/ck_bottom_2025_metat_read_counts ~/data/metat/oxblood_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/ck_middle_2025_metat_read_counts ~/data/metat/oxblood_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/ck_top_2025_metat_read_counts ~/data/metat/oxblood_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_top_2025_metat_read_counts ~/data/metat/oxblood_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_bottom_2025_metat_read_counts ~/data/metat/oxblood_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_middle_2025_metat_read_counts ~/data/metat/oxblood_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/ck_bottom_2024_metat_read_counts ~/data/metat/oxblood_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_top_2024_metat_read_counts ~/data/metat/oxblood_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_bottom_2024_metat_read_counts ~/data/metat/oxblood_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/oxblood_borg.gff -s 2 -o ~/data/metat/oxblood_borg/n_middle_2024_metat_read_counts ~/data/metat/oxblood_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/ck_bottom_2025_metat_read_counts ~/data/metat/pink_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/ck_middle_2025_metat_read_counts ~/data/metat/pink_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/ck_top_2025_metat_read_counts ~/data/metat/pink_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_top_2025_metat_read_counts ~/data/metat/pink_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_bottom_2025_metat_read_counts ~/data/metat/pink_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_middle_2025_metat_read_counts ~/data/metat/pink_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/ck_bottom_2024_metat_read_counts ~/data/metat/pink_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_top_2024_metat_read_counts ~/data/metat/pink_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_bottom_2024_metat_read_counts ~/data/metat/pink_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/pink_borg.gff -s 2 -o ~/data/metat/pink_borg/n_middle_2024_metat_read_counts ~/data/metat/pink_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/ck_bottom_2025_metat_read_counts ~/data/metat/purple_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/ck_middle_2025_metat_read_counts ~/data/metat/purple_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/ck_top_2025_metat_read_counts ~/data/metat/purple_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_top_2025_metat_read_counts ~/data/metat/purple_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_bottom_2025_metat_read_counts ~/data/metat/purple_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_middle_2025_metat_read_counts ~/data/metat/purple_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/ck_bottom_2024_metat_read_counts ~/data/metat/purple_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_top_2024_metat_read_counts ~/data/metat/purple_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_bottom_2024_metat_read_counts ~/data/metat/purple_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/purple_borg.gff -s 2 -o ~/data/metat/purple_borg/n_middle_2024_metat_read_counts ~/data/metat/purple_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/ck_bottom_2025_metat_read_counts ~/data/metat/rose_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/ck_middle_2025_metat_read_counts ~/data/metat/rose_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/ck_top_2025_metat_read_counts ~/data/metat/rose_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_top_2025_metat_read_counts ~/data/metat/rose_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_bottom_2025_metat_read_counts ~/data/metat/rose_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_middle_2025_metat_read_counts ~/data/metat/rose_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/ck_bottom_2024_metat_read_counts ~/data/metat/rose_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_top_2024_metat_read_counts ~/data/metat/rose_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_bottom_2024_metat_read_counts ~/data/metat/rose_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/rose_borg.gff -s 2 -o ~/data/metat/rose_borg/n_middle_2024_metat_read_counts ~/data/metat/rose_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/ck_bottom_2025_metat_read_counts ~/data/metat/vermilion_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/ck_middle_2025_metat_read_counts ~/data/metat/vermilion_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/ck_top_2025_metat_read_counts ~/data/metat/vermilion_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_top_2025_metat_read_counts ~/data/metat/vermilion_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_bottom_2025_metat_read_counts ~/data/metat/vermilion_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_middle_2025_metat_read_counts ~/data/metat/vermilion_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/ck_bottom_2024_metat_read_counts ~/data/metat/vermilion_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_top_2024_metat_read_counts ~/data/metat/vermilion_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_bottom_2024_metat_read_counts ~/data/metat/vermilion_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/vermilion_borg.gff -s 2 -o ~/data/metat/vermilion_borg/n_middle_2024_metat_read_counts ~/data/metat/vermilion_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/ck_bottom_2025_metat_read_counts ~/data/metat/mercury_mini_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/ck_middle_2025_metat_read_counts ~/data/metat/mercury_mini_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/ck_top_2025_metat_read_counts ~/data/metat/mercury_mini_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_top_2025_metat_read_counts ~/data/metat/mercury_mini_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_bottom_2025_metat_read_counts ~/data/metat/mercury_mini_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_middle_2025_metat_read_counts ~/data/metat/mercury_mini_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/ck_bottom_2024_metat_read_counts ~/data/metat/mercury_mini_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_top_2024_metat_read_counts ~/data/metat/mercury_mini_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_bottom_2024_metat_read_counts ~/data/metat/mercury_mini_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mercury_mini_borg.gff -s 2 -o ~/data/metat/mercury_mini_borg/n_middle_2024_metat_read_counts ~/data/metat/mercury_mini_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/ck_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/ck_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/ck_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_top_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_bottom_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_middle_2025_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/ck_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_like/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_top_2024_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_bottom_2024_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/saturn_mini_borg_like.gff -s 2 -o ~/data/metat/saturn_mini_borg_like/n_middle_2024_metat_read_counts ~/data/metat/saturn_mini_borg_like/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/ck_bottom_2025_metat_read_counts ~/data/metat/ruby_borg_related/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/ck_middle_2025_metat_read_counts ~/data/metat/ruby_borg_related/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/ck_top_2025_metat_read_counts ~/data/metat/ruby_borg_related/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_top_2025_metat_read_counts ~/data/metat/ruby_borg_related/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_bottom_2025_metat_read_counts ~/data/metat/ruby_borg_related/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_middle_2025_metat_read_counts ~/data/metat/ruby_borg_related/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/ck_bottom_2024_metat_read_counts ~/data/metat/ruby_borg_related/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_top_2024_metat_read_counts ~/data/metat/ruby_borg_related/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_bottom_2024_metat_read_counts ~/data/metat/ruby_borg_related/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/ruby_borg_related.gff -s 2 -o ~/data/metat/ruby_borg_related/n_middle_2024_metat_read_counts ~/data/metat/ruby_borg_related/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/ck_bottom_2025_metat_read_counts ~/data/metat/black_borg/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/ck_middle_2025_metat_read_counts ~/data/metat/black_borg/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/ck_top_2025_metat_read_counts ~/data/metat/black_borg/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_top_2025_metat_read_counts ~/data/metat/black_borg/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_bottom_2025_metat_read_counts ~/data/metat/black_borg/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_middle_2025_metat_read_counts ~/data/metat/black_borg/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/ck_bottom_2024_metat_read_counts ~/data/metat/black_borg/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_top_2024_metat_read_counts ~/data/metat/black_borg/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_bottom_2024_metat_read_counts ~/data/metat/black_borg/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/black_borg.gff -s 2 -o ~/data/metat/black_borg/n_middle_2024_metat_read_counts ~/data/metat/black_borg/n_middle_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/ck_bottom_2025_metat_read_counts ~/data/metat/linear_ece_19kb/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/ck_middle_2025_metat_read_counts ~/data/metat/linear_ece_19kb/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/ck_top_2025_metat_read_counts ~/data/metat/linear_ece_19kb/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_top_2025_metat_read_counts ~/data/metat/linear_ece_19kb/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_bottom_2025_metat_read_counts ~/data/metat/linear_ece_19kb/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_middle_2025_metat_read_counts ~/data/metat/linear_ece_19kb/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/ck_bottom_2024_metat_read_counts ~/data/metat/linear_ece_19kb/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_top_2024_metat_read_counts ~/data/metat/linear_ece_19kb/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_bottom_2024_metat_read_counts ~/data/metat/linear_ece_19kb/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/linear_ece_19kb.gff -s 2 -o ~/data/metat/linear_ece_19kb/n_middle_2024_metat_read_counts ~/data/metat/linear_ece_19kb/n_middle_2024_metat.bam
