featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/ck_bottom_2025_metat_read_counts ~/data/metat/mp/ck_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/ck_middle_2025_metat_read_counts ~/data/metat/mp/ck_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/ck_top_2025_metat_read_counts ~/data/metat/mp/ck_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_top_2025_metat_read_counts ~/data/metat/mp/n_top_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_bottom_2025_metat_read_counts ~/data/metat/mp/n_bottom_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_middle_2025_metat_read_counts ~/data/metat/mp/n_middle_2025_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/ck_bottom_2024_metat_read_counts ~/data/metat/mp/ck_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_top_2024_metat_read_counts ~/data/metat/mp/n_top_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_bottom_2024_metat_read_counts ~/data/metat/mp/n_bottom_2024_metat.bam
featureCounts -p -T 64 -g ID -t CDS -a ~/data/mp.gff -s 2 -o ~/data/metat/mp/n_middle_2024_metat_read_counts ~/data/metat/mp/n_middle_2024_metat.bam
