interproscan.sh -i ~/data/mp_4.fa -o ~/data/interproscan/mp_4.tsv -f tsv
interproscan.sh -i ~/data/mp_1.fa -o ~/data/interproscan/mp_1.tsv -f tsv
interproscan.sh -i ~/data/mp_3.fa -o ~/data/interproscan/mp_3.tsv -f tsv
interproscan.sh -i ~/data/mp_5.fa -o ~/data/interproscan/mp_5.tsv -f tsv
interproscan.sh -i ~/data/mp_2.fa -o ~/data/interproscan/mp_2.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_1.fa -o ~/data/interproscan/jupiter_mini_borg_1.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_2.fa -o ~/data/interproscan/jupiter_mini_borg_2.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_3.fa -o ~/data/interproscan/jupiter_mini_borg_3.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_4.fa -o ~/data/interproscan/jupiter_mini_borg_4.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_6.fa -o ~/data/interproscan/jupiter_mini_borg_6.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_7.fa -o ~/data/interproscan/jupiter_mini_borg_7.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_8.fa -o ~/data/interproscan/jupiter_mini_borg_8.tsv -f tsv
interproscan.sh -i ~/data/jupiter_mini_borg_9.fa -o ~/data/interproscan/jupiter_mini_borg_9.tsv -f tsv
interproscan.sh -i ~/data/saturn_mini_borg_1.fa -o ~/data/interproscan/saturn_mini_borg_1.tsv -f tsv
interproscan.sh -i ~/data/saturn_mini_borg_2.fa -o ~/data/interproscan/saturn_mini_borg_2.tsv -f tsv
interproscan.sh -i ~/data/saturn_mini_borg_3.fa -o ~/data/interproscan/saturn_mini_borg_3.tsv -f tsv
interproscan.sh -i ~/data/saturn_mini_borg_4.fa -o ~/data/interproscan/saturn_mini_borg_4.tsv -f tsv
interproscan.sh -i ~/data/unclassified_mini_borg.fa -o ~/data/interproscan/unclassified_mini_borg.tsv -f tsv
interproscan.sh -i ~/data/unclassified_borg.fa -o ~/data/interproscan/unclassified_borg.tsv -f tsv
interproscan.sh -i ~/data/amethyst_borg.fa -o ~/data/interproscan/amethyst_borg.tsv -f tsv
interproscan.sh -i ~/data/oxblood_borg.fa -o ~/data/interproscan/oxblood_borg.tsv -f tsv
interproscan.sh -i ~/data/pink_borg.fa -o ~/data/interproscan/pink_borg.tsv -f tsv
interproscan.sh -i ~/data/purple_borg.fa -o ~/data/interproscan/purple_borg.tsv -f tsv
interproscan.sh -i ~/data/rose_borg.fa -o ~/data/interproscan/rose_borg.tsv -f tsv
interproscan.sh -i ~/data/vermilion_borg.fa -o ~/data/interproscan/vermilion_borg.tsv -f tsv
interproscan.sh -i ~/data/mercury_mini_borg.fa -o ~/data/interproscan/mercury_mini_borg.tsv -f tsv
interproscan.sh -i ~/data/saturn_mini_borg_like.fa -o ~/data/interproscan/saturn_mini_borg_like.tsv -f tsv
interproscan.sh -i ~/data/ruby_borg_related.fa -o ~/data/interproscan/ruby_borg_related.tsv -f tsv
interproscan.sh -i ~/data/black_borg.fa -o ~/data/interproscan/black_borg.tsv -f tsv
interproscan.sh -i ~/data/linear_ece_19kb.fa -o ~/data/interproscan/linear_ece_19kb.tsv -f tsv
